// Generated by the Google Wallet setup workflow.
// Signed Google Wallet save links are safe to publish; private credentials are never stored here.
window.GOOGLE_WALLET_LINKS = {
  saints: "",
  pelicans: "",
  city: "",
  benson: ""
};
